In [1]:
print("Once upon a time, there was a cat.\nIt loved to chase mice.\nAnd it always returned home safely.")

Once upon a time, there was a cat.
It loved to chase mice.
And it always returned home safely.


In [2]:
word = "PYTHON"
print("*" * 8)
print("*", word, "*")
print("*" * 8)

********
* PYTHON *
********


In [3]:
print(1, 2, 3, 4, 5, sep=" -> ")

1 -> 2 -> 3 -> 4 -> 5


In [4]:
print("Hello!", end=" ")
print("How are you?")

Hello! How are you?


In [5]:
num = 12.34567
print(f"{num:.2f}")

12.35


In [6]:
name = input("Enter your name: ")
color = input("Enter your favorite color: ")
print(f"Hi {name}, {color} looks great on you!")

Hi Sheheryar, Green looks great on you!


In [7]:
age = int(input("Enter your age: "))
year_2050_age = age + (2050 - 2026)
print("You will be", year_2050_age, "years old in 2050")

You will be 46 years old in 2050


In [8]:
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
print("Multiplication result:", num1 * num2)

Multiplication result: 18


In [9]:
word = input("Enter a word: ")
times = int(input("Enter number of times: "))
print(word * times)

GiveGiveGive


In [10]:
total_bill = float(input("Enter total bill amount: "))
people = int(input("Enter number of people: "))
print("Each person owes:", total_bill / people)

Each person owes: 400.0


In [11]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Remainder:", a % b)

Remainder: 1


In [12]:
x = int(input("Enter base x: "))
y = int(input("Enter exponent y: "))
print("x^y =", x ** y)

x^y = 1679616


In [13]:
a = int(input("Enter numerator: "))
b = int(input("Enter denominator: "))
print("Floor division:", a // b)
# Floor division always gives an integer result

Floor division: 2


In [14]:
num = int(input("Enter a number: "))
print(num > 100)

True


In [15]:
a = int(input("Enter a: "))
b = int(input("Enter b: "))
a = a + b
b = a - b
a = a - b
print("After swap: a =", a, "b =", b)

After swap: a = 6 b = 4


In [16]:
score = 0
score += 10
score -= 3
print("Final score:", score)

Final score: 7


In [17]:
PI = 3.14159
radius = float(input("Enter radius: "))
area = PI * radius ** 2
print("Area of circle:", area)

Area of circle: 12.56636


In [18]:
first_name = "Me"
last_name = "Doe"
full_name = first_name + " " + last_name
print("Full name:", full_name)

Full name: Me Doe


In [19]:
a = "Hello"
b = 10
c = 3.5
print(type(a), type(b), type(c))

<class 'str'> <class 'int'> <class 'float'>


In [20]:
x = 10
print(x)
x = "Now I'm a string"
print(x)

10
Now I'm a string


In [21]:
num = int(input("Enter a number: "))
if num % 2 == 0:
    print("Even")
else:
    print("Odd")

Odd


In [22]:
score = int(input("Enter score: "))
if score >= 90:
    print("A")
elif score >= 80:
    print("B")
elif score < 60:
    print("F")

F


In [23]:
age = int(input("Enter age: "))
if age >= 18:
    print("Enter")
else:
    print("Wait", 18 - age, "years")

Enter


In [24]:
secret = "python123"
password = input("Enter password: ")
if password == secret:
    print("Access Granted")
else:
    print("Access Denied")

Access Denied


In [25]:
year = int(input("Enter year: "))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(year, "is a leap year")
else:
    print(year, "is not a leap year")

2023 is not a leap year


In [26]:
i = 10
while i > 0:
    print(i)
    i -= 1
print("Blast off!")

10
9
8
7
6
5
4
3
2
1
Blast off!


In [27]:
for i in range(1, 11):
    print(5 * i)

5
10
15
20
25
30
35
40
45
50


In [28]:
total = 0
while True:
    num = int(input("Enter number (0 to stop): "))
    if num == 0:
        break
    total += num
print("Total sum:", total)

Total sum: 9


In [29]:
text = input("Enter a string: ")
count = 0
for letter in text:
    if letter == "a":
        count += 1
print("Number of a's:", count)

Number of a's: 1


In [30]:
while True:
    word = input("Type 'stop' to end: ")
    if word.lower() == "stop":
        break

In [31]:
grocery = ["Eggs","Bread","Butter","Cheese","Juice"]
grocery[1] = "Milk"
grocery.pop()
print(grocery)

['Eggs', 'Milk', 'Butter', 'Cheese']


In [32]:
numbers = list(range(1, 11))
print(numbers[3:7])  # middle four numbers

[4, 5, 6, 7]


In [34]:
phone_book = {"Ali":12345,"Ahmed":67890,"Sara":54321}
print(phone_book["Ahmed"])

67890


In [35]:
nums = [1,2,2,3,3,4,5,5]
unique_nums = list(set(nums))
print(unique_nums)

[1, 2, 3, 4, 5]


In [37]:
coord = (10, 20)
# coord[0] = 15  # ❌ Error because tuples are immutable
print(coord)

(10, 20)


In [39]:
import numpy as np
matrix = np.arange(1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
arr = np.arange(1,17).reshape(4,4)
print(arr[0,-1])  # top-right corner

4


In [41]:
arr = np.random.randint(1,100,(5,5))
print(arr[2])  # 3rd row

[10 91 43 70 48]


In [42]:
arr = np.arange(1,37).reshape(6,6)
sub_grid = arr[2:4,2:4]  # center 2x2
print(sub_grid)

[[15 16]
 [21 22]]


In [43]:
identity = np.eye(3)
identity[1,1] = 10
print(identity)

[[ 1.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0.  1.]]
